source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
inhibit_all_warnings!


target 'EJHttpClientDemo' do

pod 'EJHttpClient’, :git => 'https://github.com/iOnRoad/EJHttpClient.git'

end
